Dev
CMSCompOps/AAAOps pull request #7
Opened 2017-06-23 12:01 UTC by EnginEren

Requesting merge..

2017-06-27 09:53 UTC, zvada requested changes
Concern is about filename `list_eu_final.allow` which needs to be more generic that regional redirectors admins can simply download and just put in the xrootd config file to read allow list. Therefore, could you prepare for allow list directory structure as follows, please:

* Federation/out/allow/{us,eu}/cms.{whitelist,blacklist}

...practically it would mean we'd have for EU `cms.whitelist` and `cms.blacklist` as final file to download by regional redirectors admins. To be more clear:

1) For EU admins download location and needed files would be:
`Federation/out/allow/eu/cms.{whitelist,blackslit}`

2) For US admins download location and needed files would be:
`Federation/out/allow/us/cms.{whitelist,blackslit}`

For the 2) - does your script creates also US cms.whitelist? Or how hard it would be make it so?

Thanks,
Marian

2017-06-30 11:15 UTC, EnginEren commented
Hi Marian, sorry for late action again..

I have created : 
- https://github.com/CMSCompOps/AAAOps/blob/Dev/Federation/out/allow/eu/cms.whitelist
- https://github.com/CMSCompOps/AAAOps/blob/Dev/Federation/out/allow/us/cms.whitelist

Let's not merge now since I realized that there are a lot of garbage in the repos. I will clean them. Plus, I will also create cms.blacklist files..

Cheers,
Engin

2017-07-18 15:18 UTC, zvada approved these changes

2017-07-18 15:20 UTC, zvada commented
@EnginEren: why not merge now and then do a clean up which follow up pull request on clean up action?

2017-07-19 06:48 UTC, merged